<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_DEBUG' => '1',
  'APP_SECRET' => '67d829bf61dc5f87a73fd814e2c9f629',
  'DATABASE_URL' => 'sqlite:///%kernel.project_dir%/data/database.sqlite',
  'MAILER_URL' => 'null://localhost',
);
