version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: sf4_nginx
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/nginx/conf.d/default.conf
          - .:/code
        depends_on:
          - php

    mysql:
        image: mysql:8
        container_name: sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"        
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4

    php:
        build: 
          context: .
          dockerfile: .docker/php-fpm
        container_name: sf4_php
        volumes:
          - .:/code
        depends_on:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8088:80
        links:
            - mysql

    redis:
        image: redis
        container_name: sf4_redis
        ports:
          - 6379:6379